# SonarQube project configuration
sonar.projectKey=msn5566_employemanagementsystem
sonar.projectName=employemanagementsystem
sonar.projectVersion=1.0
sonar.java.binaries=target/classes
sonar.sources=src/main
sonar.tests=src/test
sonar.java.source=17
sonar.java.target=17
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqa_8c10e73b31b7f19da1ffe9bb66737f10d1cced01
