<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="Order">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="OrderId" type="xs:string" minOccurs="0"/>
                <xs:element name="OrderDate" type="xs:date" minOccurs="0"/>
                <xs:element name="Customer" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CustomerId" type="xs:string" minOccurs="0"/>
                            <xs:element name="Name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3"/>
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                             </xs:element>
                            <xs:element name="Contact" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Email" type="xs:string"/>
                                        <xs:element name="Phone" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Items" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Item" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ItemId">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="2"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Description" type="xs:string" minOccurs="0"/>
                                        <xs:element name="Quantity" type="xs:integer">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Price" type="xs:decimal" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Billing" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CustomerId" type="xs:string" minOccurs="0"/>
                            <xs:element name="TotalAmount">
                                 <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0.01"/>
                                        <xs:maxInclusive value="100000.0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Paid" type="xs:boolean" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="PurchaseOrder">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Id" type="xs:string" minOccurs="0"/>
                <xs:element name="Date" type="xs:date" minOccurs="0"/>
                <xs:element name="Client" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Id" type="xs:string" minOccurs="0"/>
                            <xs:element name="FullName">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3"/>
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Email" type="xs:string"/>
                            <xs:element name="Phone" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Products" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Product" maxOccurs="100" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Code">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="2"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Name" type="xs:string" minOccurs="0"/>
                                        <xs:element name="Qty" type="xs:integer">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="UnitPrice" type="xs:decimal" minOccurs="0" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Payment" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CustomerId" type="xs:string" minOccurs="0"/>
                            <xs:element name="Amount">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0.01"/>
                                        <xs:maxInclusive value="100000.0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Status" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>